# BTE-Companion Configuration File
#
# command-only: If true, players can only use the command /companion. If false, players get a companion automatically in their inventory when they join the server.
# enable-custom-tpll: Uses /cs tpll from BTETools (restart required)
# enable-custom-tp: Use /tpp to teleport to a player (restart required)
# IP: HUB server
# port: HUB server
# trees-spawn-point: Spawn point of the custom trees platform
# map-spawn-point: Spawn point of the countries map
#
Companion:
  command-only: false
  enable-custom-tpll: true
  enable-custom-tp: true
  IP: localhost
  port: 00000
  trees-spawn-point:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
  map-spawn-point:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0